/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.analysis.low.level.api.fir;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.analysis.low.level.api.fir.TestGeneratorKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/low-level-api-fir/testData/designationByPsi")
@TestDataPath("$PROJECT_ROOT")
public class ScriptDesignationByPsiTestGenerated extends AbstractScriptDesignationByPsiTest {
  private void run(String fileName) {
    runTest("analysis/low-level-api-fir/testData/designationByPsi/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDesignationByPsi() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/low-level-api-fir/testData/designationByPsi"), Pattern.compile("^(.+)\\.(kts)$"), null, true);
  }

  @Test
  @TestMetadata("classInitializerScript.kts")
  public void testClassInitializerScript() {
    run("classInitializerScript.kts");
  }

  @Test
  @TestMetadata("deeplyNestedMemberPropertyScript.kts")
  public void testDeeplyNestedMemberPropertyScript() {
    run("deeplyNestedMemberPropertyScript.kts");
  }

  @Test
  @TestMetadata("deeplyNestedMemberScript.kts")
  public void testDeeplyNestedMemberScript() {
    run("deeplyNestedMemberScript.kts");
  }

  @Test
  @TestMetadata("memberFunctionScript.kts")
  public void testMemberFunctionScript() {
    run("memberFunctionScript.kts");
  }

  @Test
  @TestMetadata("memberPropertyScript.kts")
  public void testMemberPropertyScript() {
    run("memberPropertyScript.kts");
  }

  @Test
  @TestMetadata("nestedClassScript.kts")
  public void testNestedClassScript() {
    run("nestedClassScript.kts");
  }

  @Test
  @TestMetadata("primaryConstructorScript.kts")
  public void testPrimaryConstructorScript() {
    run("primaryConstructorScript.kts");
  }

  @Test
  @TestMetadata("script.kts")
  public void testScript() {
    run("script.kts");
  }

  @Test
  @TestMetadata("scriptInitializer.kts")
  public void testScriptInitializer() {
    run("scriptInitializer.kts");
  }

  @Test
  @TestMetadata("scriptResult.kts")
  public void testScriptResult() {
    run("scriptResult.kts");
  }

  @Test
  @TestMetadata("scriptWithResult.kts")
  public void testScriptWithResult() {
    run("scriptWithResult.kts");
  }

  @Test
  @TestMetadata("secondaryConstructorScript.kts")
  public void testSecondaryConstructorScript() {
    run("secondaryConstructorScript.kts");
  }

  @Test
  @TestMetadata("topLevelClassScript.kts")
  public void testTopLevelClassScript() {
    run("topLevelClassScript.kts");
  }

  @Test
  @TestMetadata("topLevelFunctionScript.kts")
  public void testTopLevelFunctionScript() {
    run("topLevelFunctionScript.kts");
  }

  @Test
  @TestMetadata("topLevelPropertyScript.kts")
  public void testTopLevelPropertyScript() {
    run("topLevelPropertyScript.kts");
  }

  @Test
  @TestMetadata("typeAliasScript.kts")
  public void testTypeAliasScript() {
    run("typeAliasScript.kts");
  }
}
